### ISSUE TITLE
Having to encode `request.body`

### ISSUE THREAD

**Issue by lovelydinosaur** [encode/requests-async#12]
In the adapter class we're currently encoding the body of the `PreparedRequest` instance, with `request.body.encode("utf-8")`.

I'm not certain why it isn't already represented as a byte interface, or how to change that, since the current "hey let's just encode it with utf-8, that must be right" is rather brittle.

**Comment by yeraydiazdiaz** [comment]
Thanks for starting this project 🌟 

When running `await requests.post('https://example.org', data=b'{"foo": "bar"}')`
I'm getting `AttributeError: 'bytes' object has no attribute 'encode'`, due to the fact that the body is indeed `bytes`. Am I missing something?

**Comment by mekicha** [comment]
@yeraydiazdiaz  I think that's because you passed in a byte. And requests tries to encode it here: https://github.com/encode/requests-async/blob/master/requests_async/adapters.py#L59

which won't work as it is already encoded.

@tomchristie  It seems from [here](https://github.com/kennethreitz/requests/blob/75bdc998e2d430a35d869b2abf1779bd0d34890e/requests/models.py#L207) that requests encodes the data already?

**Comment by yeraydiazdiaz** [comment]
I've investigated a bit more, seems `requests` does not actually do any encoding and [will `urlencode` the data if it's a dict or otherwise simply return the data unmodified if it is `str` or `bytes`](https://github.com/kennethreitz/requests/blob/75bdc998e2d430a35d869b2abf1779bd0d34890e/requests/models.py#L82-L107).

Puzzled by this I traced a simple request until I found where the actual encoding happens, turns out it's all the way in the [standard library's `http` client](https://github.com/python/cpython/blob/3.6/Lib/http/client.py#L149-L161) and [defaults to `latin-1`](https://github.com/python/cpython/blob/3.6/Lib/http/client.py#L1281-L1284):

```
-> requests.get('https://httpbin.org', data='foobar')
[13]   /Users/yeray/code/personal/_forks/requests/requests/api.py(75)get()
-> return request('get', url, params=params, **kwargs)
[14]   /Users/yeray/code/personal/_forks/requests/requests/api.py(60)request()
-> return session.request(method=method, url=url, **kwargs)
[15]   /Users/yeray/code/personal/_forks/requests/requests/sessions.py(533)request()
-> resp = self.send(prep, **send_kwargs)
[16]   /Users/yeray/code/personal/_forks/requests/requests/sessions.py(646)send()
-> r = adapter.send(request, **kwargs)
[17]   /Users/yeray/code/personal/_forks/requests/requests/adapters.py(449)send()
-> timeout=timeout
[18]   /Users/yeray/.pyenv/versions/3.6.8/envs/requests-async/lib/python3.6/site-packages/urllib3/connectionpool.py(600)urlopen()
-> chunked=chunked)
[19]   /Users/yeray/.pyenv/versions/3.6.8/envs/requests-async/lib/python3.6/site-packages/urllib3/connectionpool.py(354)_make_request()
-> conn.request(method, url, **httplib_request_kw)
[20]   /Users/yeray/.pyenv/versions/3.6.8/lib/python3.6/http/client.py(1239)request()
-> self._send_request(method, url, body, headers, encode_chunked)
[21] > /Users/yeray/.pyenv/versions/3.6.8/lib/python3.6/http/client.py(1284)_send_request()
-> body = _encode(body, 'body')
[22]   /Users/yeray/.pyenv/versions/3.6.8/lib/python3.6/http/client.py(152)_encode()
-> return data.encode("latin-1")
```

I think we should take the same approach trusting the PreparedRequest body, maybe even using the std lib's `_encode` function.

**Comment by yeraydiazdiaz** [comment]
Tracing a request with a JSON payload, i.e. `requests.get('https://httpbin.org', json=dict(foo='bar'))`, it looks like [requests does the encoding to UTF-8](https://github.com/kennethreitz/requests/blob/75bdc998e2d430a35d869b2abf1779bd0d34890e/requests/models.py#L462-L468) which is readily available as `bytes` by the time it reaches our adapter and raises an `AttributeError` on our call to `encode('utf-8')`.

**Comment by lovelydinosaur** [comment]
Note that JSON is different - it's mandated to be a utf-8 binary encoding.

**Comment by lovelydinosaur** [comment]
Pushed version 0.1.4
