### ISSUE TITLE
requests-futures

### ISSUE THREAD

**Issue by blueyed** [encode/requests-async#36]
What do you think of https://github.com/ross/requests-futures?
Is it worth adding to alternatives in the README?

**Comment by lovelydinosaur** [comment]
Maybe.
Big difference with requests-futures is that it's about multi-threaded requests rather than async/await, which means that:

* Yes, you can use it issue several simultaneous requests.
* But they're still thread-blocking, so you can only serve relatively small number of concurrent requests, rather than with async/await where the tasks are so lightweight that you can serve thousands or tens of thousands of concurrent requests.

I'm a yes on this if we also include anything else in a similar category (eg. I think there's a greenlet based approach too, right?)

Closing this off, but happy to continue the discussion, and happy to consider docs PRs here.
